set up the environment

In [1]:
import torch
import numpy as np

# Initializing a Tensor
from data

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

from a Numpy array 

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

from another tensor

In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensot: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensot: 
 tensor([[0.4679, 0.2207],
        [0.8858, 0.6378]]) 



# shape is a tuple of tensor dimensions
shape(3,2,1) <br>
3表示第一维度有3个元素
2表示第二维度有2个元素
1表示第三维度有1个元素

In [5]:
shape = (3,2,1)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n ")

Random Tensor: 
 tensor([[[0.5098],
         [0.0531]],

        [[0.5325],
         [0.9979]],

        [[0.2096],
         [0.3144]]]) 
 


Tensor的属性

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


move tensor to GPU if possible

In [7]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    

Tensor indexing and slicing

In [8]:
tensor = torch.ones(4,4)

print("First row:" , tensor[0])
print("First column:", tensor[:, 0])
print("Last column:", tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


jion the tensor together

In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [10]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])